#!/bin/bash
#######################
# domain
#######################
if grep -q '^domain' /etc/resolv.conf;then
    domain=$(awk '/domain/ {print $2}' /etc/resolv.conf)
    echo "0 domain_resolv status=0;;;; OK - domain: $domain"
elif grep -q '^search' /etc/resolv.conf;then
    domain=$(awk '/search/ {print $2}' /etc/resolv.conf)
    echo "0 domain_resolv status=0;;;; OK - domain: $domain"
else
    echo "2 domain_resolv status=0;;;; CRIT - domain:"
fi

#######################
# nameserver
#######################
nameserver=$(awk '/^nameserver/ {print $2}' /etc/resolv.conf | tr '\n' ',')
echo "0 nameserver status=0;;;; OK - nameservers: $nameserver"
