#!/bin/bash
if grep -q '^domain' /etc/resolv.conf;then
    domain=$(awk '/domain/ {print $2}' /etc/resolv.conf)
elif grep -q '^search' /etc/resolv.conf;then
    domain=$(awk '/search/ {print $2}' /etc/resolv.conf)
else
    domain=
fi

if [ -e /etc/xensource-inventory ];then
    . /etc/xensource-inventory
    syslog_destination=$(xe host-param-get param-name=logging param-key=syslog_destination uuid=$INSTALLATION_UUID)
    pif_uuid=$(xe pif-list management=true host-uuid=$INSTALLATION_UUID --minimal)
    pif_domain=$(xe pif-param-get param-name=other-config param-key=domain uuid=$pif_uuid)
    pif_dns=$(xe pif-param-get param-name=DNS uuid=$pif_uuid)
fi
echo "0 pif_dns status=0;;;; OK - DNS: $pif_dns"
echo "0 domain_mgmt_pif status=0;;;; OK - domain: $pif_domain"
echo "0 domain_resolv status=0;;;; OK - domain: $domain"
echo "0 syslog_destination status=0;;;; OK - syslog_destination: $syslog_destination"
echo "0 version_salt-minion status=0;;;; OK - version: $(rpm -q --qf "%{VERSION}" salt-minion)"
echo "0 domain_resolv status=0;;;; OK - domain: $domain"
