all_hosts += ["xs221.gdcloud.com|wato|state_up|/" + FOLDER_PATH + "/",]
all_hosts += ["xs223.gdcloud.com|wato|state_up|/" + FOLDER_PATH + "/",]
all_hosts += ["xs222.gdcloud.com|wato|state_up|/" + FOLDER_PATH + "/",]
all_hosts += ["xs224.gdcloud.com|wato|state_up|/" + FOLDER_PATH + "/",]
all_hosts += ["xs225.gdcloud.com|wato|state_up|/" + FOLDER_PATH + "/",]
