# Written by WATO
# encoding: utf-8

all_hosts += [
  "xs02|state_up|wato|/" + FOLDER_PATH + "/",
  "xs03|state_up|wato|/" + FOLDER_PATH + "/",
  "xs04|state_up|wato|/" + FOLDER_PATH + "/",
  "xs05|state_up|wato|/" + FOLDER_PATH + "/",
  "xs06|lan|obj_server|cmk-agent|tcp|os_other|state_up|prod|wato|/" + FOLDER_PATH + "/",
  "xs07|state_up|wato|/" + FOLDER_PATH + "/",
]


# Host attributes (needed for WATO)
host_attributes.update(
{'xs02': {'alias': None,
          'ipaddress': None,
          'snmp_community': None,
          'tag_agent': None,
          'tag_criticality': None,
          'tag_networking': None,
          'tag_os': None,
          'tag_rack_obj': None,
          'tag_state': 'state_up'},
 'xs03': {'alias': None,
          'ipaddress': None,
          'snmp_community': None,
          'tag_agent': None,
          'tag_criticality': None,
          'tag_networking': None,
          'tag_os': None,
          'tag_rack_obj': None,
          'tag_state': 'state_up'},
 'xs04': {'alias': None,
          'ipaddress': None,
          'snmp_community': None,
          'tag_agent': None,
          'tag_criticality': None,
          'tag_networking': None,
          'tag_os': None,
          'tag_rack_obj': None,
          'tag_state': 'state_up'},
 'xs05': {'alias': None,
          'ipaddress': None,
          'snmp_community': None,
          'tag_agent': None,
          'tag_criticality': None,
          'tag_networking': None,
          'tag_os': None,
          'tag_rack_obj': None,
          'tag_state': 'state_up'},
 'xs06': {},
 'xs07': {'alias': None,
          'ipaddress': None,
          'snmp_community': None,
          'tag_agent': None,
          'tag_criticality': None,
          'tag_networking': None,
          'tag_os': None,
          'tag_rack_obj': None,
          'tag_state': 'state_up'}})
