#!/usr/bin/env python
# check XenServer patches status
import pprint
import XenAPI
import sys

sess = XenAPI.xapi_local()
try:
    sess.login_with_password('', '')
    xenapi = sess.xenapi
    this_record = xenapi.session.get_this_host(sess._session)
    this_host = xenapi.host.get_record(this_record)

    ref = sess.xenapi.pool.get_all()[0]
    pool = sess.xenapi.pool.get_record(ref)
    pool_master = sess.xenapi.host.get_record(pool['master'])
    if this_host['name_label'] == pool_master['name_label']:
        this_host['role'] = 'master'
    else:
        this_host['role'] = 'slave'

    info = {
        'edtion': this_host['edition'],
        'hostname': this_host['hostname'],
        'address': this_host['address'],
        'role': this_host['role'],
        'enabled': this_host['enabled'],
        'iscsi_iqn': this_host['other_config']['iscsi_iqn'],
        'boot_time': this_host['other_config']['boot_time'],
        'memory_overhead': this_host['memory_overhead'],
    }

    print "<<<XenAPI_host>>>"
    for key, val in info.items():
        print "%-16s: %s" % (key, val)

except Exception, e:
    sys.exit('error: %s' % str(e))
