#!/usr/bin/env python
import sys, os

if not os.path.exists('/etc/xensource-inventory'):
    sys.exit()
else:
    import XenAPI

sess = XenAPI.xapi_local()
try:
    sess.login_with_password('', '')
    xenapi = sess.xenapi

    ref = xenapi.session.get_this_host(sess._session)
    ref_metric = xenapi.host.get_metrics(ref)
    metrics = xenapi.host_metrics.get_record(ref_metric)
    memory_free = metrics['memory_free']
    memory_total = metrics['memory_total']

    print '<<<XenAPI_host_metrics>>>'
    for key, val in metrics.items():
        print "%-14s: %s" % (key, val)

except Exception, e:
    sys.exit('error: %s' % str(e))
