#!/usr/bin/env python
# check XenServer patches status
import pprint
import XenAPI
import sys

def pprinter(data):
   pp = pprint.PrettyPrinter()
   return pp.pprint(data)

sess = XenAPI.xapi_local()

try:
    sess.login_with_password('', '')
    xenapi = sess.xenapi

    this_record = xenapi.session.get_this_host(sess._session)
    this_host = xenapi.host.get_record(this_record)

    host_patch_refs = this_host['patches']

    check_item = '''<<<XenAPI_pool_patch>>>'''
    print check_item
    for host_patch_ref in host_patch_refs:
        host_patch = xenapi.host_patch.get_record(host_patch_ref)
        pool_patch_ref = host_patch['pool_patch']
        pool_patch = xenapi.pool_patch.get_record(pool_patch_ref)

        patch_applied = host_patch['applied']
        patch_timestamp_applied = host_patch['timestamp_applied']

        patch_size = pool_patch['size']
        patch_name_label = pool_patch['name_label']
        patch_name_description = pool_patch['name_description']

        #colums: applied host name_description name_label other_config pool_patch size timestamp_applied uuid version'
        print patch_name_label, patch_applied, patch_timestamp_applied, patch_size, patch_name_description

except Exception, e:
    sys.exit('error: %s' % str(e))
