<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: omdadmin
 * Date: Wed, 09 Apr 2014 04:21:50 +0000
 */

$conf['title'] = 'Dokuwiki site01';
$conf['lang'] = 'zh';
$conf['template'] = 'arctictut';
$conf['license'] = 'cc-by-sa';
$conf['youarehere'] = 1;
$conf['fullpath'] = 1;
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['htmlok'] = 1;
$conf['phpok'] = 1;
$conf['userewrite'] = '2';
$conf['tpl']['arctictut']['sidebar'] = 'left';
$conf['tpl']['arctictut']['left_sidebar_content'] = 'index';
$conf['multisite']['authfile'] = '/omd/sites/site01/var/check_mk/wato/auth/auth.php';
$conf['multisite']['auth_secret'] = '/omd/sites/site01/etc/auth.secret';
$conf['multisite']['auth_serials'] = '/omd/sites/site01/etc/auth.serials';
$conf['multisite']['htpasswd'] = '/omd/sites/site01/etc/htpasswd';
$conf['tpl']['vector']['vector_navigation_location'] = 'sidebar';

// end auto-generated content
