#!/usr/bin/python
#coding:utf-8
import sys
'''
run check_mk-agent local checks by salt
'''

try:
    import salt.client
    local = salt.client.LocalClient()
except:
    sys.exit()

script_path = 'cmk/agent/files/local/60/xs_info'
ret = local.cmd('os:XenServer', 'cmd.script', ["salt://%s" % script_path], expr_form='grain')
#ret = local.cmd('xsm02', 'cmd.script', ["salt://%s" % script_path])

#import pprint
#print pprint.pformat(ret)
for minion_id in ret.keys():
    stdout = ret[minion_id]['stdout']
    print "<<<<%s>>>>" % minion_id
    print "<<<local>>>"
    print stdout
    print "<<<<>>>>"
