#!/usr/bin/env python
import sys, os

if not os.path.exists('/etc/xensource-inventory'):
    sys.exit()
else:
    import XenAPI

sess = XenAPI.xapi_local()
try:
    sess.login_with_password('', '')
    xenapi = sess.xenapi

    this_record = xenapi.session.get_this_host(sess._session)
    this_host = xenapi.host.get_record(this_record)

    print '<<<XenServer_NAS>>>'
    for ref in this_host['PBDs']:
        PBD = xenapi.PBD.get_record(ref)
        device_config = PBD['device_config']
        if device_config.has_key('server'):
            nas = "%s:%s" % (device_config['server'], device_config['serverpath'])
            print nas

#    del this_host['PIFs']
#    del this_host['host_CPUs']
#    del this_host['patches']
#    del this_host['resident_VMs']
#    del this_host['PCIs']
#    del this_host['metrics']

except Exception, e:
    sys.exit('error: %s' % str(e))
