#!/usr/bin/env python
import pprint
import sys, os

if not os.path.exists('/etc/xensource-inventory'):
    sys.exit()
else:
    import XenAPI

sess = XenAPI.xapi_local()
try:
    sess.login_with_password('', '')
    xenapi = sess.xenapi

    this_record = xenapi.session.get_this_host(sess._session)
    this_host = xenapi.host.get_record(this_record)
    refs = this_host['resident_VMs']

    print '<<<XenAPI_resient_VMs>>>'
    for ref in refs:
        VM = xenapi.VM.get_record(ref)
        if VM['is_control_domain'] == False:
            name_label = VM['name_label']
            print name_label

except Exception, e:
    sys.exit('error: %s' % str(e))
