#!/usr/bin/env python
# check XenServer patches status
import pprint
import XenAPI
import sys

sess = XenAPI.xapi_local()
try:
    sess.login_with_password('', '')
    xenapi = sess.xenapi
    this_record = xenapi.session.get_this_host(sess._session)
    this_host = xenapi.host.get_record(this_record)

    check_item = '''<<<license_params>>>'''
    print check_item
    for key, val in this_host['license_params'].items():
        print "%-35s: %s" % (key, val)

except Exception, e:
    sys.exit('error: %s' % str(e))
