#!/usr/bin/env python
import sys, os

if not os.path.exists('/etc/xensource-inventory'):
    sys.exit()
else:
    import XenAPI

sess = XenAPI.xapi_local()
try:
    sess.login_with_password('', '')
    xenapi = sess.xenapi

    this_record = xenapi.session.get_this_host(sess._session)
    this_host = xenapi.host.get_record(this_record)

    print '<<<XenAPI_host_PBDs>>>'
    for ref in this_host['PBDs']:
        PBD = xenapi.PBD.get_record(ref)
        print "[%s]" % PBD['uuid']
        print "  currently_attached: %s" % PBD['currently_attached']

        device_config = PBD['device_config']
        for key, val in device_config.items():
            print "%20s: %s" % (key, val)

except Exception, e:
    sys.exit('error: %s' % str(e))
