#!/usr/bin/env python
import sys, os

if not os.path.exists('/etc/xensource-inventory'):
    sys.exit()
else:
    import XenAPI

sess = XenAPI.xapi_local()
try:
    sess.login_with_password('', '')
    xenapi = sess.xenapi

    this_record = xenapi.session.get_this_host(sess._session)
    this_host = xenapi.host.get_record(this_record)

    print '<<<XenAPI_host_PBDs>>>'
    for ref in this_host['PBDs']:
        PBD = xenapi.PBD.get_record(ref)
        device_config = PBD['device_config']
        if 'serverpath' in device_config.keys():
            pbd = "server  : %s%s" % (device_config['server'], device_config['serverpath'])
        elif 'legacy_mode' in device_config.keys():
            pbd = "location: %s %s" % (device_config['location'], device_config['legacy_mode'])
        elif 'device' in device_config.keys():
            pbd = "device  : %s" % device_config['device']
        elif 'location' in device_config.keys():
            pbd = "location: %s" % device_config['location']
        print pbd

except Exception, e:
    sys.exit('error: %s' % str(e))
