#!/usr/bin/env python
import sys, os

if not os.path.exists('/etc/xensource-inventory'):
    sys.exit()
else:
    import XenAPI

sess = XenAPI.xapi_local()
pbd = {}
try:
    sess.login_with_password('', '')

    this_record = sess.xenapi.session.get_this_host(sess._session)
    this_host = sess.xenapi.host.get_record(this_record)

    ref = sess.xenapi.pool.get_all()[0]
    pool = sess.xenapi.pool.get_record(ref)
    pool_master = sess.xenapi.host.get_record(pool['master'])
    default_SR = sess.xenapi.SR.get_record(pool['default_SR'])

    pbd = {
        'default_SR': default_SR['name_label'],
        'master': pool_master['name_label'],
        'name': pool['name_label'],
    }

    print "<<<XenAPI_pool>>>"
    for key, val in pbd.items():
        print "%-10s: %s" % (key, val)

except Exception, e:
    sys.exit('error: %s' % str(e))
