#!/usr/bin/python
#coding:utf-8
import sys
'''
check_mk local check plugin by salt module: status.cpuinfo
'''

try:
    import salt.client
    local = salt.client.LocalClient()
except:
    sys.exit()

ret = local.cmd('os:XenServer', 'status.cpuinfo', expr_form='grain')

for minion_id in ret.keys():
    print "<<<<%s>>>>" % minion_id
    print "<<<local>>>"
    print "0 status.cpuinfo.model_name status=0;;;; %s" % ret[minion_id]['model name']
    print "0 status.cpuinfo.cpu_MHz. status=0;;;; %s" % ret[minion_id]['cpu MHz']
    print "0 status.cpuinfo.cpu_cores. status=0;;;; %s" % ret[minion_id]['cpu cores']
    print "<<<<>>>>"
