#!/bin/bash
if ! which salt-key > /dev/null 2>&1;then
    exit
fi

MINIONS=$(salt-key -l acc --output=txt | sed -n '2,$p')
UP=0
DOWN=0
for minion in $MINIONS
do
    result=$(salt $minion test.ping --output=txt)
    if echo $result | grep -q True;then
        let UP=$UP+1
    else
        let DOWN=$DOWN+1
    fi
done

COUNT=
if [ $DOWN -gt 0 ];then
    STATE=1
    STATE_TEXT="WARN - minions down: $DOWN"
    COUNT=$DOWN
else
    STATE=0
    STATE_TEXT="OK - all minions up($UP)"
    COUNT=$UP
fi

echo "$STATE minion.state minions=$COUNT;;;; $STATE_TEXT"
