#!/usr/bin/python
#coding:utf-8
import sys
'''
check salt-minion status by salt '*' test.ping
'''

try:
    import salt.client
    local = salt.client.LocalClient()
except:
    sys.exit()

ret = local.cmd('*', 'test.ping')

for minion_id in ret.keys():
    if ret[minion_id]:
        print "0 salt.test.ping_{0} - OK - {1}".format(minion_id, ret[minion_id])
    else:
         print "1 salt.test.ping_{0} - WARN - {1}".format(minion_id, ret[minion_id])
